name: calme
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  loader_overlay: ^2.2.0
  flutter_spinkit: ^5.2.0
  sizer: ^2.0.15
  google_fonts: any
  unicons: ^2.1.1
  timeline_tile: ^2.0.0
  flutter_svg_provider: any
  flutter_svg: any
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.5
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/core/logo.png"
  web:
    generate: true
    image_path: "assets/core/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/core/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/core/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
     - assets/core/
     - assets/landing/
     - assets/home/
     - assets/people/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700