name: calme
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.1
  sizer: ^2.0.15
  google_fonts: any
  unicons: ^2.1.1
  timeline_tile: ^2.0.0
  flutter_svg_provider: any
  flutter_svg: any
  percent_indicator: ^4.2.3
  another_flushbar: ^1.12.30
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  json_annotation: ^4.9.0
  logger: ^2.2.0
  skeletonizer: ^1.1.2+1
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  firebase_auth: ^4.19.5
  flutter_card_swiper: ^7.0.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.5
  flutter_launcher_icons: "^0.13.1"
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/core/logo.png"
  web:
    generate: true
    image_path: "assets/core/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/core/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/core/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
     - assets/core/
     - assets/landing/
     - assets/home/
     - assets/people/
     - assets/coping/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700